export interface UseCaseDefinition {
  id: string;
  name: string;
  description: string;
  actor: 'User' | 'Helpdesk';
  approvalRequired: boolean;
  category: string;
}

export const supportUseCases: UseCaseDefinition[] = [
  { id: 'SUC001', name: 'Reset My Password', description: 'Allows users to reset their password securely', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC002', name: 'Unlock My Account', description: 'Unlocks the user account after lockout', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC003', name: 'Force Password Change Next Login', description: 'Forces password change during next login', actor: 'Helpdesk', approvalRequired: false, category: 'Identity' },
  { id: 'SUC004', name: 'Check Password Expiry Status', description: 'Shows password expiry details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC005', name: 'Check Last Password Change Date', description: 'Displays when password was last changed', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC006', name: 'Reset SSPR Registration', description: 'Resets self-service password reset registration', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC007', name: 'Check SSPR Enrollment Status', description: 'Checks whether SSPR is configured', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC008', name: 'Reset My MFA Methods', description: 'Clears all MFA methods for fresh setup', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC009', name: 'Force MFA Re-registration', description: 'Forces user to register MFA again', actor: 'Helpdesk', approvalRequired: false, category: 'Identity' },
  { id: 'SUC010', name: 'Check MFA Enrollment Status', description: 'Shows whether MFA is enabled and configured', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC011', name: 'View Registered MFA Methods', description: 'Lists registered authentication methods', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC012', name: 'Remove Old Authenticator Device', description: 'Removes old Microsoft Authenticator device', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC013', name: 'Remove Old Phone Number', description: 'Removes outdated MFA phone number', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC014', name: 'Generate Temporary Access Pass', description: 'Creates a temporary access pass for login recovery', actor: 'Helpdesk', approvalRequired: true, category: 'Identity' },
  { id: 'SUC015', name: 'Check Temporary Access Pass Validity', description: 'Shows TAP expiry and status', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC016', name: 'Remove Email Auth Method', description: 'Removes email as authentication method', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC017', name: 'Revoke Passwordless Login', description: 'Disables passwordless authentication', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC018', name: 'View My Profile', description: 'Displays full user profile details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC019', name: 'Update Mobile Number', description: 'Updates mobile number in Entra ID', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC020', name: 'Update Alternate Email', description: 'Updates alternate email address', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC021', name: 'Update Office Location', description: 'Updates office location details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC022', name: 'Update Preferred Language', description: 'Updates language preference', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC023', name: 'Update Emergency Contact', description: 'Updates emergency contact details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC024', name: 'Check My Manager', description: 'Shows assigned manager details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC025', name: 'View My Team Structure', description: 'Shows reporting team hierarchy', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC026', name: 'Sign Me Out Everywhere', description: 'Signs out user from all active sessions', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC027', name: 'Revoke My Active Sessions', description: 'Revokes all active authentication tokens', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC028', name: 'View My Active Sessions', description: 'Lists active login sessions', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC029', name: 'Terminate Specific Session', description: 'Terminates selected active session', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC030', name: 'View My Sign-in History', description: 'Shows recent sign-in history', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC031', name: 'View Failed Sign-ins', description: 'Displays failed login attempts', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC032', name: 'View Sign-in Locations', description: 'Shows login locations and IP history', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC033', name: 'Report Suspicious Login', description: 'Allows reporting suspicious login activity', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC034', name: 'Confirm Safe Login', description: 'Allows user to confirm legitimate login activity', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC035', name: 'View My Registered Devices', description: 'Lists all devices linked to account', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC036', name: 'Remove Old Device from Account', description: 'Removes stale or unused devices', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC037', name: 'Mark Device Lost', description: 'Marks a registered device as lost', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC038', name: 'Check Device Compliance Status', description: 'Displays device compliance details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC039', name: 'Request Group Access', description: 'Requests access to a security or M365 group', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC040', name: 'Request Application Access', description: 'Requests access to enterprise applications', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC041', name: 'Request Shared Mailbox Access', description: 'Requests access to a shared mailbox', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC042', name: 'Request Distribution List Access', description: 'Requests membership in a distribution list', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC043', name: 'Request Role Elevation (Temporary)', description: 'Requests temporary admin privilege elevation', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC044', name: 'Request Guest Invitation', description: 'Requests guest account invitation', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC045', name: 'Check My Account Status', description: 'Displays active/block status of account', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC046', name: 'Check If My Account Is Blocked', description: 'Confirms if account is blocked from sign-in', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC047', name: 'View My Assigned Roles', description: 'Shows assigned Entra roles', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC048', name: 'View My Assigned Licenses', description: 'Lists active licenses assigned', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC049', name: 'Check License Expiry', description: 'Shows expiry or renewal details for licenses', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC050', name: 'View My Access Summary', description: 'Summarizes all access rights and roles', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC051', name: 'Check If My Account Is Risky', description: 'Shows if account has any risk alerts', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC052', name: 'Acknowledge Risk Alert', description: 'Confirms risk alert acknowledgement', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC053', name: 'Request Account Recovery', description: 'Initiates recovery workflow for compromised account', actor: 'User', approvalRequired: true, category: 'Identity' },
  { id: 'SUC054', name: 'Report Compromised Account', description: 'Flags account as compromised for investigation', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC055', name: 'Check Recovery Status', description: 'Tracks current recovery request progress', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC056', name: 'Find My Manager Contact', description: 'Retrieves manager contact details', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC057', name: 'Find My Team Members', description: 'Lists team members under same manager', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC058', name: 'Find My Department Members', description: 'Lists members in same department', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC059', name: 'View My Reporting Chain', description: 'Shows reporting hierarchy upwards', actor: 'User', approvalRequired: false, category: 'Identity' },
  { id: 'SUC060', name: 'Find Internal Contact', description: 'Searches internal employee directory', actor: 'User', approvalRequired: false, category: 'Identity' }
];
